### ISSUE TITLE
Block on dropping SyncWrapper.

### ISSUE THREAD

**Issue by xuxiaocheng0201** [bikeshedder/deadpool#330]
When I removing the sqlite db file, I occurred an os error 32.
`Error: 另一个程序正在使用此文件，进程无法访问。 (os error 32)`
It means `Another program is using this file and the process cannot access it`.
This is a common error in windows.

I have found the code that caused this problem.
In [SyncWrapper](https://github.com/bikeshedder/deadpool/blob/master/sync/src/lib.rs#L158-L166), the connection resource will be dropped in a background task. However, I have no way of knowing whether this task has been completed or not. So if I remove the db file immediately after dropping the pool, this error will occur.

So is there any way to ensure the connections is completely dropped? or block on when the `SyncWrapper` is dropping?

Reproduce:
`Cargo.toml`:
```toml
anyhow = "^1.0"
tokio = { version = "^1.0", features = ["macros", "rt-multi-thread"] }
rusqlite = { version = "~0.31", features = ["bundled"] }
r2d2_sqlite = "~0.24"
r2d2 = "~0.8"
deadpool-r2d2 = "~0.4"
```
`main.rs`:
```rust
use std::fs::remove_file;
use anyhow::Result;
use deadpool_r2d2::Runtime;
use r2d2_sqlite::SqliteConnectionManager;

pub type Manager = deadpool_r2d2::Manager<SqliteConnectionManager>;
pub type Pool = deadpool_r2d2::Pool<Manager>;

#[tokio::main]
async fn main() -> Result<()> {
    // Create the sqlite database pool.
    let pool = Pool::builder(Manager::new(SqliteConnectionManager::file("1.db"), Runtime::Tokio1)).build()?;

    // Perform a simple query.
    pool.get().await?.interact(|c| c.execute("CREATE TABLE db(id INTEGER);", [])).await.unwrap()?;

    // Close the pool.
    pool.close();
    drop(pool);

    // Remove the database file.
    remove_file("1.db")?; // Error here.
    Ok(())
}
```
